name: tenants

services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
