[project]
name = "owerflow-core"
version = "0.1.0"
description = "core pkg for sms-be"
readme = "README.md"
requires-python = ">=3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/owerflow_core"]
